package moves

import (
	"fmt"
	"mkdata/utils"
	"reflect"
	"strings"
)

func (s *State) Write() {
  // write preamble on everything
  v := reflect.ValueOf(&s.Files).Elem()
  for i := 0; i < v.NumField(); i++ {
    field := v.Field(i)
    if field.Kind() != reflect.Struct { continue }
    if !field.CanAddr() { continue }
    b, ok := field.Addr().Interface().(*strings.Builder)
    if !ok { continue }
    b.WriteString("; autogenerated, do not edit\n")
  }

  // now write specifics
  counter := 0
  s.moves.Range(func(key, value interface{}) bool {
    k := key.(string)
    v := value.(move)
    counter++

    fmt.Fprintf(&s.Files.MoveConstants,
      "\tconst %s ; %02x\n",
      utils.NormalizeAsConstNameUnderspaces(k),
      counter)
    
    fmt.Fprintf(&s.Files.MoveNames,
      "\tli \"%s\"\n",
      v.title)
    
    fmt.Fprintf(&s.Files.MoveDesc,
      "\tdw %sDesc\n",
      utils.NormalizeAsSymbolName(k))
    
    fmt.Fprintf(&s.Files.MoveAttributes,
      "\tmove EFFECT_%s, %d, %s, %d, %d, %d ; %s\n",
      utils.NormalizeAsConstNameUnderspaces(v.constant),
      v.power,
      utils.NormalizeAsConstName(v.movetype),
      v.accuracy,
      v.pp,
      v.fxchance,
      utils.NormalizeAsConstName(k))
    
    fmt.Fprintf(&s.Files.MoveAnimations,
      "\tdw BattleAnim_%s\n",
      utils.NormalizeAsSymbolName(k))
    
    if v.cancrit {
      fmt.Fprintf(&s.Files.CritMoves,
        "\tdw %s\n",
        utils.NormalizeAsConstNameUnderspaces(k))
    }
    return true
  })
}
