package items

import (
	"fmt"
	"mkdata/utils"
	"reflect"
	"strings"
)

func (s *State) Write() {
  // write preamble on everything
  v := reflect.ValueOf(&s.Files).Elem()
  for i := 0; i < v.NumField(); i++ {
    field := v.Field(i)
    if field.Kind() != reflect.Struct { continue }
    if !field.CanAddr() { continue }
    b, ok := field.Addr().Interface().(*strings.Builder)
    if !ok { continue }
    b.WriteString("; autogenerated, do not edit\n")
  }

  // now write specifics
  s.item.Range(func(key, value interface{}) bool {
    k := key.(string)
    v := value.(item)
    
    fmt.Fprintf(&s.Files.NormalItemConstants,
      "\tconst %s\n", utils.NormalizeAsConstNameUnderspaces(k),
    )
    fmt.Fprintf(&s.Files.NormalItemNames,
      "\tdb \"%s\"\n", utils.NormalizeName(v.title),
    )
    fmt.Fprintf(&s.Files.NormalItemAttributes,
      "\t; %s\n"+
				"\titem_attribute %d, HELD_%s, %d, %s, %s, ITEMMENU_%s, ITEMMENU_%s\n",
			k,
			v.price,
			utils.NormalizeAsConstName(v.heldEffect),
			v.parameter,
			utils.NormalizeAsConstNameUnderspaces(v.property),
			"ITEM",
			utils.NormalizeAsConstNameUnderspaces(v.fieldSelectAction),
			utils.NormalizeAsConstNameUnderspaces(v.battleSelectAction),
    )
    fmt.Fprintf(&s.Files.NormalItemEffects,
      "\tdw %sEffect ; %s\n", utils.NormalizeAsSymbolName(v.fieldEffect), utils.NormalizeAsConstNameUnderspaces(k),
    )
    fmt.Fprintf(&s.Files.NormalItemDesc,
      "\tdw %sDesc\n", utils.NormalizeAsSymbolName(k),
    )
    return true
  })

  s.key.Range(func(key, value interface{}) bool {
    k := key.(string)
    v := value.(item)
    
    fmt.Fprintf(&s.Files.KeyItemConstants,
      "\tconst %s\n", utils.NormalizeAsConstNameUnderspaces(k),
    )
    fmt.Fprintf(&s.Files.KeyItemNames,
      "\tdb \"%s\"\n", utils.NormalizeName(v.title),
    )
    fmt.Fprintf(&s.Files.KeyItemAttributes,
      "\t; %s\n"+
				"\titem_attribute %d, HELD_%s, %d, %s, %s, ITEMMENU_%s, ITEMMENU_%s\n",
			k,
			v.price,
			utils.NormalizeAsConstName(v.heldEffect),
			v.parameter,
			utils.NormalizeAsConstNameUnderspaces(v.property),
			"KEY_ITEM",
			utils.NormalizeAsConstNameUnderspaces(v.fieldSelectAction),
			utils.NormalizeAsConstNameUnderspaces(v.battleSelectAction),
    )
    fmt.Fprintf(&s.Files.KeyItemEffects,
      "\tdw %sEffect ; %s\n", utils.NormalizeAsSymbolName(v.fieldEffect), utils.NormalizeAsConstNameUnderspaces(k),
    )
    fmt.Fprintf(&s.Files.KeyItemDesc,
      "\tdw %sDesc\n", utils.NormalizeAsSymbolName(k),
    )
    return true
  })

  s.ball.Range(func(key, value interface{}) bool {
    k := key.(string)
    v := value.(item)
    
    fmt.Fprintf(&s.Files.BallItemConstants,
      "\tconst %s\n", utils.NormalizeAsConstNameUnderspaces(k),
    )
    fmt.Fprintf(&s.Files.BallItemNames,
      "\tdb \"%s\"\n", utils.NormalizeName(v.title),
    )
    fmt.Fprintf(&s.Files.BallItemAttributes,
      "\t; %s\n"+
				"\titem_attribute %d, HELD_%s, %d, %s, %s, ITEMMENU_%s, ITEMMENU_%s\n",
			k,
			v.price,
			utils.NormalizeAsConstName(v.heldEffect),
			v.parameter,
			utils.NormalizeAsConstNameUnderspaces(v.property),
			"BALL",
			utils.NormalizeAsConstNameUnderspaces(v.fieldSelectAction),
			utils.NormalizeAsConstNameUnderspaces(v.battleSelectAction),
    )
    fmt.Fprintf(&s.Files.BallItemEffects,
      "\tdw %sEffect ; %s\n", utils.NormalizeAsSymbolName(v.fieldEffect), utils.NormalizeAsConstNameUnderspaces(k),
    )
    fmt.Fprintf(&s.Files.BallItemDesc,
      "\tdw %sDesc\n", utils.NormalizeAsSymbolName(k),
    )
    return true
  })
}
